const DB_NAME="botoeira-sons-db",STORE="sounds",COUNT=50;
const board=document.getElementById("board"),editor=document.getElementById("editor"),status=document.getElementById("status"),dot=document.getElementById("statusDot"),configBtn=document.getElementById("configBtn"),saveConfigBtn=document.getElementById("saveConfigBtn"),banner=document.getElementById("configBanner"),hint=document.getElementById("hint"),slotNumber=document.getElementById("slotNumber"),soundName=document.getElementById("soundName"),soundFile=document.getElementById("soundFile"),fileInfo=document.getElementById("fileInfo"),message=document.getElementById("editorMessage");
let db,configMode=false,selected=0,currentAudio=null,currentUrl=null,playing=-1;
let slots=Array.from({length:COUNT},(_,i)=>({id:i,name:`Botão ${i+1}`,fileName:"",blob:null}));
const pending=new Map();

function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function all(){return new Promise((ok,no)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function commitChanges(){return new Promise((ok,no)=>{const tx=db.transaction(STORE,"readwrite"),store=tx.objectStore(STORE);for(const [id,item] of pending){item===null?store.delete(id):store.put(item)}tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}

function stop(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0}if(currentUrl)URL.revokeObjectURL(currentUrl);currentAudio=null;currentUrl=null;playing=-1;status.textContent="Pronto para tocar.";dot.classList.remove("playing");render()}
async function play(i){const s=slots[i];if(!s.blob)return;stop();currentUrl=URL.createObjectURL(s.blob);currentAudio=new Audio(currentUrl);playing=i;status.textContent=`Tocando: ${s.name}`;dot.classList.add("playing");render();currentAudio.addEventListener("ended",stop,{once:true});try{await currentAudio.play()}catch{stop();status.textContent="Não foi possível reproduzir este áudio."}}
function openEdit(i){selected=i;const s=slots[i];slotNumber.textContent=String(i+1).padStart(2,"0");soundName.value=s.blob?s.name:"";soundFile.value="";fileInfo.textContent=s.fileName?`Áudio atual: ${s.fileName}`:"Nenhum áudio configurado.";message.textContent="";editor.showModal()}
function render(){board.innerHTML="";let visible=0;slots.forEach((s,i)=>{if(!configMode&&!s.blob)return;visible++;const b=document.createElement("button");b.type="button";b.className=`pad${playing===i?" playing":""}${configMode?" editable":""}`;const n=document.createElement("span");n.className="num";n.textContent=String(i+1).padStart(2,"0");const sym=document.createElement("span");sym.className="symbol";sym.textContent=configMode?"⚙":playing===i?"🔊":"▶";const lab=document.createElement("span");lab.className="label";lab.textContent=s.blob?s.name:"Adicionar áudio";b.append(n,sym,lab);if(configMode){const mark=document.createElement("span");mark.className="edit-mark";mark.textContent="EDITAR";b.append(mark)}b.addEventListener("click",()=>configMode?openEdit(i):play(i));board.append(b)});if(!configMode&&visible===0){const empty=document.createElement("div");empty.className="empty-state";empty.textContent="Nenhum áudio configurado. Clique em “Configurar” para adicionar sons.";board.append(empty)}}

configBtn.addEventListener("click",()=>{configMode=true;configBtn.classList.add("hidden");saveConfigBtn.classList.remove("hidden");banner.classList.remove("hidden");hint.textContent="Configuração liberada: clique nos botões para adicionar, trocar ou remover os áudios.";render()});
saveConfigBtn.addEventListener("click",async()=>{try{await commitChanges();pending.clear();configMode=false;saveConfigBtn.classList.add("hidden");configBtn.classList.remove("hidden");banner.classList.add("hidden");hint.textContent="Clique em um botão configurado para reproduzir o som.";editor.close();status.textContent="Configuração salva. Edição bloqueada.";render()}catch(e){console.error(e);status.textContent="Não foi possível salvar a configuração."}});
document.getElementById("stopAll").addEventListener("click",stop);
document.getElementById("closeEditor").addEventListener("click",()=>editor.close());
soundFile.addEventListener("change",()=>{const f=soundFile.files?.[0];fileInfo.textContent=f?`Selecionado: ${f.name} • ${(f.size/1048576).toFixed(2)} MB`:(slots[selected].fileName?`Áudio atual: ${slots[selected].fileName}`:"Nenhum áudio configurado.")});
document.getElementById("applySound").addEventListener("click",()=>{const f=soundFile.files?.[0],old=slots[selected];if(!f&&!old.blob){message.textContent="Selecione um arquivo de áudio.";return}if(f&&!f.type.startsWith("audio/")){message.textContent="Escolha um arquivo de áudio válido.";return}const item={id:selected,name:(soundName.value.trim()||(f?f.name.replace(/\.[^.]+$/,""):old.name)).slice(0,30),fileName:f?f.name:old.fileName,blob:f||old.blob};slots[selected]=item;pending.set(selected,item);message.textContent="Alteração aplicada. Use “Salvar configuração” quando terminar.";fileInfo.textContent=`Áudio atual: ${item.fileName}`;render()});
document.getElementById("removeSound").addEventListener("click",()=>{if(playing===selected)stop();slots[selected]={id:selected,name:`Botão ${selected+1}`,fileName:"",blob:null};pending.set(selected,null);soundName.value="";soundFile.value="";fileInfo.textContent="Nenhum áudio configurado.";message.textContent="Removido desta configuração. Clique em “Salvar configuração” quando terminar.";render()});
document.getElementById("testSound").addEventListener("click",async()=>{const f=soundFile.files?.[0];if(f){stop();currentUrl=URL.createObjectURL(f);currentAudio=new Audio(currentUrl);status.textContent=`Testando: ${f.name}`;dot.classList.add("playing");currentAudio.addEventListener("ended",stop,{once:true});try{await currentAudio.play()}catch{stop()}}else if(slots[selected].blob)play(selected);else message.textContent="Selecione um áudio para testar."});

(async()=>{render();try{db=await openDB();(await all()).forEach(x=>{if(Number.isInteger(x.id)&&x.id>=0&&x.id<COUNT)slots[x.id]=x});render()}catch(e){console.error(e);status.textContent="Não foi possível abrir o armazenamento local."}})();